### ISSUE TITLE
Error running docker image

### ISSUE THREAD

**Issue by dachafra** [anifledramos/tfm-rdf#4]
at the end 
```
invalid argument "type=bind,source=/Users/dchaves/Documents/proyectos/tfms/tfm-rdf/data," for "--mount" flag: invalid field '' must be a key=value pair
See 'docker run --help'.
```

**Comment by dachafra** [comment]
if you want to expose data with the host I would recommend you to use volumes `-v`

**Comment by anifledramos** [comment]
Can you specify your OS? It seems that if you are working in Windows it might have issues with mounting folders. 

This Dockerfile was configured to run in Linux just to test if everything worked fine and give the opportunity to run against machines with big memory, but if you only want to test if everything works fine and you don't plan to test files bigger than 1GB (which can be handled locally in machines with 16GB Mem) it is not necessary to do so for now, so I removed the mount for the moment. Anyway I will take a closer look on how volumes work to change that. 

Related to other issues, I realized that Docker does not support sudo, so the Makefile for both JNITriples and JNIDictionary has to remain how it was, but I already changed prepare.sh so it can run locally and do the work while Dockerfile can run smoothly too.

**Comment by dachafra** [comment]
macOS Big Sur 11.4
Docker version 20.10.6

**Comment by dachafra** [comment]
now works
